name: llmgateway

services:
  redis:
    container_name: redis
    image: redis:8
    command: ["redis-server", "--protected-mode", "no", "--bind", "0.0.0.0"]
    restart: always
    ports:
      - "6379:6379"
    environment:
      CI: ${CI}
